### ISSUE TITLE
Data Explorer: some columns incorrectly displayed as Dates

### ISSUE THREAD

**Issue by fedebertolini** [scaphold-io/scaphold-issues#19]
The Data Explorer is displaying some `String` and `Float` properties as `Date`s. I inspected the graphql query response and the data is correct. You can compare the values for `area` and `rentBase` displayed in the Data Explorer and returned by the GraphQL query:

<img width="976" alt="screen shot 2017-02-19 at 19 25 57" src="https://cloud.githubusercontent.com/assets/1497562/23105119/d808e3aa-f6d9-11e6-8f9c-63793cc82743.png">

Some other properties like `rentTotal`, `address` and `postalCode` are also incorrectly displayed as Dates.

**Comment by mikeparisstuff** [comment]
Thanks for bringing this up. I will get this fixed.

**Comment by mikeparisstuff** [comment]
This has been fixed and will go up in the next deployment 👍

**Comment by fedebertolini** [comment]
Awesome! 👍

**Comment by mikeparisstuff** [comment]
Pushed this update and it should be fixed. Thanks.

**Comment by fedebertolini** [comment]
hi @mlp5ab, I'm still experiencing the same problem. I did a hard refresh on the page, but still seeing date values in string/number columns

**Comment by fedebertolini** [comment]
Ok, I can finally see the correct data in the Explorer. Thanks!
